### ISSUE TITLE
Data persistance

### ISSUE THREAD

**Issue by kmajeed** [sequenceiq/docker-ambari#101]
Hi

Does this docker image allow data persistence? i.e. consider the following

     1. I perform docker pull, initialize my HDP services
     2. Upload some data files in HDFS and Hive etc
     3. Shut down docker 
     4. Restart docker image

Will my data persist between restarts, and do I have to setup services like Hive, Pig etc every time I restart docker and upload my files in HDFS?

**Comment by martonsereg** [comment]
Hi, you can use volume sharing to persist data between docker restarts by mounting a volume (or volumes) from the host to the container with the `-v` switch when starting the ambari container, then configure HDFS to use that volume as data dir.

**Comment by azimut** [comment]
Documentation about what volumes use would be helpful.
