### ISSUE TITLE
public-hostname.sh no longer works in non-cloud environment.

### ISSUE THREAD

**Issue by dlyle65535** [sequenceiq/docker-ambari#102]
Commit 61f8cc771a88408b3f733d4883cc783022a5ec9a removed the logic that tests which cloud platform the container is running on. Hostnames are incorrect on locally run containers. This causes the UI links to point to strange locations.

**Comment by lalyos** [comment]
thanks for reporting. I'm actually working on getting the local deployment working, and that is one issue you pointed out, the other is the revrse dns lookup which is needed by some hadoop services.

im already able to use gliderlabs/resolvable for single host deployment, so i'll will include that fallback for `hostname -f` as well.
