### ISSUE TITLE
Why change SSHD port to 2022?

### ISSUE THREAD

**Issue by micooz** [sequenceiq/docker-ambari#114]
After change SSHD port to 2022 (#113),  `Confirm Hosts` step of `CLUSTER INSTALL WIZARD` failed when using ambari web ui.

![qq20160220-0 2x](https://cloud.githubusercontent.com/assets/8897063/13196829/e902d4de-d814-11e5-91bb-eafcf88d2008.png)

And the log here:

```
==========================
Creating target directory...
==========================

Command start time 2016-02-20 12:50:40

ssh: connect to host amb2 port 22: Connection refused
SSH command execution finished
host=amb2, exitcode=255
Command end time 2016-02-20 12:50:40

ERROR: Bootstrap of host amb2 fails because previous action finished with non-zero exit code (255)
ERROR MESSAGE: ssh: connect to host amb2 port 22: Connection refused

STDOUT: 
ssh: connect to host amb2 port 22: Connection refused
```

How do I setup ambari cluster correctly?

**Comment by mhmxs** [comment]
First of all thanks for the report. i picked it up, and fix in a few hour.

**Comment by mhmxs** [comment]
So ambari-functions uses the lastest docker images and i burned the fix into them.

**Comment by micooz** [comment]
@mhmxs Thanks for your timely fix, now amb-server can connect to agents but encountered another problem:

```
==========================
Creating target directory...
==========================

Command start time 2016-02-21 07:01:59

Warning: Permanently added 'amb1,172.17.0.4' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
SSH command execution finished
host=amb1, exitcode=255
Command end time 2016-02-21 07:01:59

ERROR: Bootstrap of host amb1 fails because previous action finished with non-zero exit code (255)
ERROR MESSAGE: Warning: Permanently added 'amb1,172.17.0.4' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

STDOUT: 
Warning: Permanently added 'amb1,172.17.0.4' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```

I guess it's the issue of setting up password-less ssh login, and I have no idea to fix it. Any suggestion?

**Comment by mhmxs** [comment]
Can i ask which version do you use? On the latest master we are using unstable Ambari version, so i suggest to use [2.1.2-v9](https://github.com/sequenceiq/docker-ambari/tree/2.1.2-v9), which was our last stable version. At [ambari-functions](https://github.com/sequenceiq/docker-ambari/blob/2.1.2-v9/ambari-functions#L11) you should change the Ambari container version.
