### ISSUE TITLE
Best/Recommended upgrade path from Ambari 2.1/HDP 2.3 to Ambari 2.2/HDP 2.4 ?

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/docker-ambari#123]
Hi,

We use a cloudbreak based cluster with HDP :
* CB was 1.1.0 and was upgraded to 1.2.1
* We use so far HDP 2.3.4 and want to upgrade to 2.4.0

I was wondering what's the best way to update ambari ; is it just to pull a new version of the container or to update ambari within existing container ?

I would expect the first by doing following workflow:
* Pull new docker-ambari image on all hosts
* Restart ambari-server container on ambari host
* Restart ambari-agent container on all remaining nodes

My only question was ; are there some information that cloudbreak may have put in the current container that I need to copy/paste in the new ones ?

Once Ambari is up to date, I thnk that HDP upgrade is as simple as following the docs ;-)

Thanks,
Nicolas

**Comment by doktoric** [comment]
Hi,

Unfortunately currently we do not have tested solution for upgrade ambari in a cloudbreak deployed cluster. You can export your blueprint in ambari and then deploy a new cluster with cloudbreak which will contains the same services.
If you want to follow the manual process which was described above then you have to map the volumes on the host and linking the ambari server with the ambari db container.
Currently we are starting the containers with api calls. You can see here the details: 
https://github.com/sequenceiq/cloudbreak/blob/release-1.2/core/src/main/java/com/sequenceiq/cloudbreak/core/bootstrap/service/ContainerConstraintFactory.java
 
Br, 
R

**Comment by nsteinmetz** [comment]
Ok, thanks for the answer ; I'll recreate a cluster from scratch to have a clean platform.

Thanks,
Nicolas

I let you chose if it should remain open till you have an upgrade path or close it otherwise.
