### ISSUE TITLE
mysql-connector-java-5.1.17.jar is outdated and doesn't work with RDS

### ISSUE THREAD

**Issue by liammac** [sequenceiq/docker-ambari#124]
The mysql-connector-java-5.1.17.jar connector no longer works with RDS we need a way to sub in our own or update this to at least mysql-connector-java-5.1.35.jar which does work.

Currently it looks like it's baked into the base docker image 
https://github.com/sequenceiq/docker-ambari/

Attempted to do this via a recipe but the problems are as follows. 

-Recipes don't run on the amber host so cannot overwrite the jar before it's pushed out
-Post install recipes can replace the jar on the hive server2 machine but there's no way to restart hive server 2 from the recipe leading to further issues.

**Comment by mhmxs** [comment]
Hi @liammac ,

We don't use these containers in production any more, so we won't put extra effort to make it customizable. I could imagine two possible solutions:
- Send me a pull request with updated and tested mysql version
- Fork project and do it on your way
