### ISSUE TITLE
RFI: Where is Dockerfile for sequenceiq/consul

### ISSUE THREAD

**Issue by blindenvy** [sequenceiq/docker-ambari#125]
Where is the source code for the sequenceiq/consul image that is used as an orchestrator for the ambari docker nodes in this repo?

**Comment by martonsereg** [comment]
Are you looking for this? https://github.com/sequenceiq/docker-consul

**Comment by bbihari** [comment]
or this? https://hub.docker.com/r/sequenceiq/consul/

**Comment by blindenvy** [comment]
Yes, I think the first link is the one I'm looking for... Don't know how I missed it in my github search. Thank you.
