### ISSUE TITLE
Question: How can I access the Ambari UI from outside the host?

### ISSUE THREAD

**Issue by obaidsalikeen** [sequenceiq/docker-ambari#130]
Hi,

I used the ambari-functions script to launch a 3 node cluster, and I was also able to access the Ambari ui on port 8080 within the host using curl.

However, how could I expose the UI, so I could access it from outside the host.
Thanks

**Comment by mhmxs** [comment]
Hi @obaidsalikeen,

Which kind of operating system do you use?

**Comment by obaidsalikeen** [comment]
I used CentOS Linux 7 for this experiment,

**Comment by mhmxs** [comment]
This `ambari-functions` is proposed to development and testing scenarios, so i couldn't suggest any easy way to expose Ambari to the host machine. But on Linux you should add some rules to the netfilter to NAT traffic from host to docker bridge.
