### ISSUE TITLE
ambari-functions do not work well on ZSH

### ISSUE THREAD

**Issue by labianchin** [sequenceiq/docker-ambari#18]
Hi

I was running the following tutorial:
http://blog.sequenceiq.com/blog/2014/09/19/apache-tez-cluster/

First, when sourcing the .amb file, in ZSH I needed to pass the full pass.
So, this does not work:
```bash
$ . .amb
```
But this work:
```bash
$ . ~/.amb
```

After when running the following command:
```bash
$ amb-deploy-cluster 4
```

I get the error:
```bash
starting an ambari cluster with: 4 nodes
run-command:2: = not found
```

In bash, this does not happens.

Thanks.

**Comment by matyix** [comment]
Thanks @coderigo for the contribution.
