### ISSUE TITLE
Documentation reports HDP 2.2 is used, when it is not

### ISSUE THREAD

**Issue by cyon666** [sequenceiq/docker-ambari#29]
Leveraging branch 1.7.0, documentation reports that Ambari 1.7.0 is leveraged, which it is. However, documentation also mentions that HDP 2.2 is leveraged, it is not:

![screen shot 2015-01-15 at 14 12 04](https://cloud.githubusercontent.com/assets/6876059/5765621/9648b73a-9cc0-11e4-96f4-ebb16e1852dd.png)

Note: Attempting to use the single line execution noted under documentation section "Multinode Hadoop Cluster" which references the following command "curl -Lo .amb j.mp/docker-ambari && . .amb && amb-deploy-cluster"

Note2: Yes - I am referencing the right docker-ambari script which calls out ambari:1.7.0 docker image and not the default one seen in the URL (which calls out 1.6)

When the cluster comes up, a user can go into the Ambari UI Admin section and determine full stack deployment versions. In the ambari UI, it clearly states that HDP 2.1 is present. Examination of the Dockerfile that is leveraged shows several issues:

1) hdp.repo = This file is incorrect for HDP 2.2 (Ref: http://dev.hortonworks.com.s3.amazonaws.com/HDPDocuments/HDP2/HDP-2-trunk/bk_installing_manually_book/content/upgrade-2X-repo.html)
2) Addition of hdp.repo to yum repository during docker image build is commented out

This is misleading to users, whom expect improvements done in HDP 2.2 to exist. Unfortunately they do not, since HDP 2.1 is what is leveraged.

However, when changing hdp.repo to full-fill the proper URLs, and uncommenting out lines 21 and 22 do not seem to help. (Ref: https://github.com/sequenceiq/docker-ambari/blob/1.7.0/ambari-server/Dockerfile)

Unfortunately I'm not quite sure how to get all this working at the moment, hence the issue being opened. Any response is appreciated!

**Comment by keyki** [comment]
I'll update it to use 2.2 blueprints.

**Comment by cyon666** [comment]
Sounds good, please let me know when this task is completed. Would love to use your 1.7.0 branch for some investigations being done by my group these days. I appreciate your responses too!

**Comment by keyki** [comment]
I completely forgot about this one, I'm updating now.

**Comment by keyki** [comment]
The new Docker image is building, you can check its progress [here](https://registry.hub.docker.com/u/sequenceiq/ambari/builds_history/21308/). Once its finished you can pull again and try. If everything works out please close this issue.

**Comment by cyon666** [comment]
Good to go! Pulled latest 1.7.0 image and ran single line command to build and deploy cluster, while leveraging the correct branch for ambari-functions.

Can confirm HDP 2.2 along with Ambari 1.7.0!

I appreciate your help on this! Closing.
