### ISSUE TITLE
Ambari 1.7.0 fails to install cluster at ~5 - 6%

### ISSUE THREAD

**Issue by IainColledge** [sequenceiq/docker-ambari#30]
As per my discussion on http://blog.sequenceiq.com/blog/2014/12/04/multinode-ambari-1-7-0/

This is running in Ubuntu server 14.04.1 LTS

Docker version info:

Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

Image: sequenceiq/ambari tag: 1.7.0 

Ambari 1.6.0 does work though.

For zipped log files from the 3 containers please let me know where I can send them.

**Comment by keyki** [comment]
Hi,

Could you please try again? We just released a new version from 1.7.0.

**Comment by IainColledge** [comment]
Thanks for this and here are my results:

It failed at 33.16% and was fast getting there so I went into the logs and these were the errors I saw.

05:15:41,007 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:41,008 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:41,009 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:41,014 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://s3.amazonaws.com/dev.hortonworks.com/HDP/hdp_urlinfo.json (s3.amazonaws.com)
05:15:41,016 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:42,916 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:42,918 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:42,919 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:42,920 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://public-repo-1.hortonworks.com/HDP/hdp_urlinfo.json (public-repo-1.hortonworks.com)
05:15:42,921 ERROR [Stack Version Loading Thread] LatestRepoCallable:89 - Could not load the URI http://s3.amazonaws.com/dev.hortonworks.com/HDP/hdp_urlinfo.json (s3.amazonaws.com)
05:16:29,589 ERROR [qtp1374522245-26] ClusterImpl:1797 - No service found for config type '{}', service config version not created

After some digging around from a basic Ubuntu or Centos image running bash resolv.conf is created and DNS lookups work fine, the new 1.7.0 image does not have a resolv.conf and is unable to resolve any DNS names.

Something to bear in mind is my setup. I'm running virtual machines on a separate network from my main subnet and my docker subnet is set to one different from default. Routing is enabled so that any subnet can talk to any other.

so:
x.x.1.x main physical LAN
x.x.100.x virtual host LAN
x.x.200.x docker LAN running in my sandbox

Routing and security set to allow traffic from any where to anywhere else.

**Comment by akanto** [comment]
Hi,

That is strange the resolve.conf shall be there, you can check it.
```bash
~ $ docker pull sequenceiq/ambari:1.7.0
~ $ docker run -i -t --entrypoint /bin/bash sequenceiq/ambari:1.7.0
bash-4.1# ls -l /etc/resolv.conf
-rw-r--r-- 1 root root 23 Feb 16 08:44 /etc/resolv.conf
```

Please note that each container has it's own /etc/hosts and /etc/resolve.conf and they are bind-mounted in from /var/lib/docker/containers/<id> automatically by Docker when the container is started and therefore the resolve.conf is not part of the Docker image.

You can check the mount point with ```docker inspect <id>```.
```
 ...
 "ProcessLabel": "",
    "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/00e57b80a2b387244788f6ae893b80955b500673cd731cef6176c4be4725e389/resolv.conf"
 ...
```

Attila

**Comment by IainColledge** [comment]
And just to mess with our heads the IT gods changed something and with a fresh docker pull it all works fine, would suggest this issue should be closed.

**Comment by matyix** [comment]
Thanks - in case you face any other issues please let us know. Usually at 5-6% we pull the RPMs from the repository - and sometimes the HDP repos are not available. This should not be an issue anymore as last week I have released a warmed up container, where all the RPMs are already inside the Docker containers. This speeds up the provisioning as well ...
