### ISSUE TITLE
mutli-node cluster builds fail because of missing nagios dependency

### ISSUE THREAD

**Issue by mccahill** [sequenceiq/docker-ambari#36]
The 1.7.0 version of the Dockerfile sets the script
      /tmp/download-warmup-deps.sh
to be executable, but never runs the script. Because the script isn't run, nagios is not available
to be installed when building multi-node clusters using default blueprints
     multi-node-hdfs-yarn
     hdp-multinode-default
and these cluster builds fail.

**Comment by matyix** [comment]
Ambari agents pull the components (e.g. nagios) from the RPM repository based on the blueprint - if the RPMs are already not pulled/available on the host (e.g. being warmed-up as in the warmup branch). 
Sometimes the RPM repository is not available - and the installation fails but that should not be related to  `/tmp/download-warmup-deps.sh`. You should check the Ambari logs (docker exec -it amb0 bash) in `/var/logs/ambari-server/ambari-server.log`. By any chance, the installation failed around 6%?

**Comment by mccahill** [comment]
The installation was failing at around 35% and only for the blueprints that wanted nagios, right at the point where it attempted to install nagios. I'm pretty sure the RPM repository is available because I can pull from it by executing the download-warmup-deps.sh from the Dockerfile.

**Comment by matyix** [comment]
merged. thx
