### ISSUE TITLE
Adding custom files into the containers

### ISSUE THREAD

**Issue by paul-lupu** [sequenceiq/docker-ambari#40]
Hello, 

We are working on building a sandbox version that has a couple of extra files for services that we need baked in. 

Is there any way we could add those file to the sequenceiq/ambari image provided here: http://blog.sequenceiq.com/blog/2014/12/04/multinode-ambari-1-7-0/ ?

**Comment by matyix** [comment]
You can build an image based on top of this (FROM) and use ADD in Dockerfile to add the files. Or keep this container as it is and use `volumes` to access files from the container.

**Comment by keyki** [comment]
You can also use volume share.

**Comment by paul-lupu** [comment]
Thanks for the input, I'll see how we'll go about it then.
