### ISSUE TITLE
ambari server can not start

### ISSUE THREAD

**Issue by neucloud** [sequenceiq/docker-ambari#45]
amb-deploy-cluster hung on "waits for ambari server". Because /var/lib/pgsql/data/postmaster.pid is exist, postgres start failed, ambari server can not start.
sequenceiq/ambari:1.7.0 sequenceiq/ambari:2.0.0 and sequenceiq/ambari:latest all have this issue.

**Comment by matyix** [comment]
Make sure you configure SELinux properly (or disable it) on the host or start the containers in `privileged` mode. This applies to all latest RHEL/CentOS where SELinux is enabled with a default policy.

This is standard Docker functionality, has nothing to do with the Ambari container.
