### ISSUE TITLE
keychain.io is insecure and not always available

### ISSUE THREAD

**Issue by threedliteguy** [sequenceiq/docker-ambari#56]
Piping to bash is not secure, and in addition the keychain.io service is not always available (currently getting python errors when confirming key upload).  Providing another way to install image would be appreciated.

Edit:  I contacted one of the developers and he said the site has not worked for some time now.

**Comment by lalyos** [comment]
Entering the ambari containers should be done via `docker exec`.

Actually, we should remove sshd completely, as it was inserted only as docker exec didn't exist at that time.
