### ISSUE TITLE
How to properly restart containers?

### ISSUE THREAD

**Issue by nawa** [sequenceiq/docker-ambari#59]
I installed sequenceiq/ambari:1.7.0 on Vagrant with Ubuntu and run cluster with 3 nodes. They were working fine and all services too. IPs of these nodes are 172.17.0.2...4
But I stopped containers and tried to restart using `docker start amb0 amb1 amb2`. Now Ambari is not see any of nodes because they are having other IPs. I think that would be better if cluster will work with any IPs of nodes

How to restart nodes properly and where is config for that hardcoded IP

**Comment by threedliteguy** [comment]
Looks like Docker is working on being able to retain static ips:
http://blog.docker.com/2015/04/docker-networking-takes-a-step-in-the-right-direction-2/#more-5307

Someone wrote a patch in the mean time:
https://github.com/pdumais/docker

**Comment by keyki** [comment]
There is no proper way to restart, yet. We'll make the Consul based Ambari feasible for local environments where we won't rely on IP addresses.
