### ISSUE TITLE
Problem adding new blueprint 

### ISSUE THREAD

**Issue by dischord01** [sequenceiq/docker-ambari#61]
I am trying to add a new blueprint that I got from querying a running cluster via the api. I saved the file in the current directory as blueprint.json and the ran the following to get the Ambari-shell;

```
docker run -it --rm -v $(pwd):/tmp -w /tmp sequenceiq/ambari-shell --ambari.host=$AMBARI_IP
Error: Unable to access jarfile ambari-shell.jar
```

And I have tried to get it from a S3 bucket and I get a error;

```
ambari-shell>blueprint add --url https://s3-us-west-1.amazonaws.com/ambari-blueprint/hdp.json
No blueprint specified
```

What is the proper way of adding blueprints form the ambari-shell?

Update:
I was however able to add the blueprint by using ADD in the Dockerfile to add it during the build. 
I am running into a issue with a customized blueprint where we added Zeppelin to our stack. 

```
ambari-shell>blueprint add --file blueprint.json
Cannot add blueprint: {
  "status" : 400,
  "message" : "The component 'ZEPPELIN_MASTER' in host group 'host_group_1' is not valid for the specified stack"
}
```

**Comment by doktoric** [comment]
This is not possible by default with ambari because the basic ambari not supporting zeppelin. You have to add Zeppelin service to the ambari stack and then you will able to install zeppelin with blueprint.
