### ISSUE TITLE
blueprint with pig and single-node-hdfs-yarn

### ISSUE THREAD

**Issue by amitadpsl** [sequenceiq/docker-ambari#62]
HI

I want to use pig and single node cluster.
Is there any blueprint that i can use?

**Comment by keyki** [comment]
Yes, https://github.com/sequenceiq/ambari-rest-client/blob/master/src/main/resources/blueprints/hdp-singlenode-default

**Comment by amitadpsl** [comment]
i am tryin to access this via docker using the following command:

 docker run -e BLUEPRINT=hdp-singlenode-default  -it -v /home/amita/git/:/share  sequenceiq/ambari:1.7.0   /bin/bash

after i use the container  the pig command fails.
Is there anything that i am missing?
