### ISSUE TITLE
ambari-server doesn't work with ambari-functions

### ISSUE THREAD

**Issue by zbears** [sequenceiq/docker-ambari#65]
I'm trying to run ambari-functions with a docker container built from your ambari-server folder's Dockerfile but it appears that that image is lacking the serf utilities required by this process. Am I looking in the wrong place? Is there somewhere for me to find a Dockerfile that will work with the ambari-functions file? I have to build it myself as I need to change the base OS for testing purposes. Thanks for any help you can provide.

**Comment by lalyos** [comment]
Hi you should use the ambari-functions script from the 2.0.0 branch:
https://raw.githubusercontent.com/sequenceiq/docker-ambari/2.0.0/ambari-functions

This will use the official sequenceiq/ambari:2.0.0 from dockerhub.

unfortunately if you build the ambar-server/Dockerfile on the master branch locally it won't work.
we will fix that soon.

**Comment by zbears** [comment]
Okay. Great. Thanks for the heads up. Will the Dockerfile from the 2.0.0 branch function with the 2.0.0 ambari-functions script?

**Comment by lalyos** [comment]
yes,

But as you can see on [ambari-functions line 12#](https://github.com/sequenceiq/docker-ambari/blob/2.0.0/ambari-functions#L12) is explicitly using the `sequenceiq/ambari:2.0.0` image. So there is no need to build it locally.

Even if you do build locally, it would be the same as the one on dockerhub. If you really want to use your local version (for example if you are hacking the Dockerfile) you have to either export the `IMAGE ` env variable or use that one:

```
docker build -t myambari ambari-server
export IMAGE=myambari
. ambari-functions
amb-start-cluster 5
```

**Comment by zbears** [comment]
Great. Thanks for the information. I'm doing deployment testing on Oracle Linux so I'm having to build from scratch to get the correct base OS. Thank you for your help and awesome work!
