### ISSUE TITLE
Ambari2.0.0 cluster creation fails

### ISSUE THREAD

**Issue by zbears** [sequenceiq/docker-ambari#66]
When using the command 
`curl -Lo .amb j.mp/docker-ambari-200 && . .amb && amb-deploy-cluster`
The cluster deploys fine, the clients connect to the master, and the ambari shell runs. 
The deployment fails with an error message: "Installation: FAILED"
This happens at about 10% configuration after the following is run:
`cluster create --exitOnFinish true`
Is there any way to debug this/has anyone else gotten it to work?

**Comment by keyki** [comment]
You can login to Ambari to see why the installation failed. Also you can run the `amb-shell` and issue the commands manually if you need to change something.

**Comment by zbears** [comment]
Great. Thanks.
