### ISSUE TITLE
Port 53 is often not available

### ISSUE THREAD

**Issue by yuzhu** [sequenceiq/docker-ambari#71]
Hi 

I am new to this, but I have noticed that amb-start-cluster tries to publish  port 53 to the host.
Often this fails because dnsmasq is often enabled with libvirt. 

Should there be a  change to the script so that it would more likely work out of the box and not conflict with popular services?

**Comment by keyki** [comment]
Can you tell me which branch do you use?

**Comment by yuzhu** [comment]
I am on master.

**Comment by mhmxs** [comment]
I suggest to use branch 2.1.0-consul which doesn't publish any ports.

**Comment by yuzhu** [comment]
I am using 2.1.0-consul image. I am using the ambari script on the master branch which uses 2.1.0-consul image. 

In fact, all I did was running
 curl -Lo .amb j.mp/docker-ambari && . .amb && amb-deploy-cluster 3

**Comment by mhmxs** [comment]
If you switch branch you have to call amb-clean and then source ambari-function again.

**Comment by mhmxs** [comment]
I merged some changes from the 2.1.0-consul branch to master, so could you please reexecute that curl command? It must fix your issue.

**Comment by mhmxs** [comment]
Thank you for the report.
