### ISSUE TITLE
Connecting to Ambari HDFS Client container

### ISSUE THREAD

**Issue by nallagangus** [sequenceiq/docker-ambari#72]
I was able to run the cluster w/o issues. I installed HDFS client on all nodes and I simply do not know how to properly connect to one of the existing nodes for leveraging "hadoop" and other commands..

So I tried docker run -dit -name "c000" -host "amb1" /bin/bash followed by "docker connect c000". I was able to connect but I do not see any of HDFS clients.. I thought above will connect me to same container I launched HDFS client to .. but seems it is different

any suggestions

**Comment by keyki** [comment]
You can jump into the containers, like `docker exec -it amb1 bash` and then `su hdfs` and you can use all of the hadoop commands.

**Comment by nallagangus** [comment]
All seems to be operational How ever when I stop containers, stop boot2docker and restart boot2docker followed by start containers. I see all components are failing. I could not restart any of "HDFS" services. Is there a "list" I need to follow before stop containers and start containers?

**Comment by keyki** [comment]
Stop/start is not implemented yet, the problem is that after restart the containers might get different IPs.

**Comment by nallagangus** [comment]
what is the best way to handle "laptop reboot" ? how can I retain IP Addresses of amb1, amb2 etc after a stop?

**Comment by keyki** [comment]
For now all you can do is to stop/remove all your containers restart b2d and create a new cluster so all the containers will get the first X IP addresses. In this way if you restart b2d the next time and start the ambari containers they will get the first X IPs again.

**Comment by nallagangus** [comment]
Got it. Pretty much make sure to stop b2d when you stop containers
