### ISSUE TITLE
How to use ambari-functions ? 

### ISSUE THREAD

**Issue by zongwan** [sequenceiq/docker-ambari#73]
I have no idea about code below:
```
docker@boot2docker:~/git/docker-ambari$ curl -Lo .amb j.mp/docker-ambari && . .amb && amb-deploy-cluster
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
```

Give me some keywords to google,please. 
Thanks.

**Comment by mhmxs** [comment]
It looks like a DNS or other network issue. You should replace j.mp/docker-ambari to https://raw.githubusercontent.com/sequenceiq/docker-ambari/master/ambari-functions.

**Comment by zongwan** [comment]
```
curl -Lo .amb https://raw.githubusercontent.com/sequenceiq/docker-ambari/master/ambari-functions && . .amb && amb-deploy-cluster
```
```
docker@boot2docker:~/git/docker-ambari$ curl -Lo .amb https://raw.githubusercontent.com/sequenceiq/docker-ambari/master/ambari-functions && . .amb && amb-deploy-cluster
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5306  100  5306    0     0   8322      0 --:--:-- --:--:-- --:--:--  8435
-sh: .amb: line 20: syntax error: bad function name
```

**Comment by mhmxs** [comment]
The default shell in boot2docker VM is sh, which doesn't support functions as well.
```
docker@boot2docker:~$ ps -p $$
  PID TTY          TIME CMD
  19277 pts/1    00:00:00 sh
```
To use the ambari-functions you have to execute it on Bash. If you are a mac user it's quite easy, because the default shell is bash. Just source ambari-functions locally. You only need to take care a routing rule, because otherwise the ambari-functions couldn't connect to the docker containers inside the VM.
```
sudo route add -net 172.17.0.0/16 192.168.59.103
```
If you are on Windows, you have to install bash
```
tce-load -wi bash
bash
```

**Comment by zongwan** [comment]
I see.
Thanks a lot.

It works fine in vagrant-opensuse12.3

**Comment by qinzhaokun** [comment]
@mhmxs Hi, I am a user in windows. I follow your step to install bash firstly, But it not works when using:

    tce-load -wi bash

it shows: bash: tce-load: command not found
I don't know where is wrong?

**Comment by mhmxs** [comment]
Hi @qinzhaokun, tce-load is the package manager of tiny core linux, so if you want to use ambari-functions, you have to log into the boot2docker machine ```boot2docker ssh```, than install bash ```tce-load -wi bash && bash``` (you could check running shell version via ```ps  -ef | grep $$ | grep -v grep | head -1```). If you are done you should clone the repo into the virtual machine and ```source ambari-functions```.

Sorry but i don't have any experience on Windows, maybe some bash implementation also works as well.
