### ISSUE TITLE
docker run not working with given command

### ISSUE THREAD

**Issue by shashank-inforworks** [sequenceiq/docker-ambari#80]
Hi,
I'm trying to use the command in the README to run the ambari-server:
```
docker run -d -P -h amb0.mycorp.kom -e KEYCHAIN=<keychain@email> --name amb0  sequenceiq/ambari --tag ambari-server=true
```
But I'm getting this error:
Error response from daemon: Cannot start container xyz: [8] System error: exec: "--tag": executable file not found in $PATH

Output of docker ps -a:
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                     PORTS               NAMES
xyz                 sequenceiq/ambari         "--tag ambari-server="   5 seconds ago       Created                                        amb0
```

Docker version:
Docker version 1.8.2, build 0a8c2e3
OS: Ubuntu 14.04

**Comment by keyki** [comment]
Hi,

I'm not sure how updated the README is, but can you try using this ```curl -Lo .amb j.mp/docker-ambari && . .amb``` and then use the ```amb-``` commands like ```amb-deploy-cluster 2```.

**Comment by shashank-inforworks** [comment]
Hi Krisztian,

Thanks for your reply. You are right, I can launch the cluster using the
.amb script, and it is fantastic.
The annoying part is, the script is using a similar command.
```
docker run -d --dns 172.17.42.1 --entrypoint
/usr/local/serf/bin/start-serf-agent.sh -e KEYCHAIN=abc@xyz.com --name hdp0
-h hdp0,xyz.com sequenceiq/ambari:1.7.0 --tag ambari-server=true
```
Looks like I need to spend a little time understanding the docker
subtelties.

Thanks,
Shashank

On Mon, Sep 28, 2015 at 4:31 PM, Krisztian Horvath <notifications@github.com

**Comment by keyki** [comment]
We switched to consul from serf a while ago, so I suggest you to use the master branch and clean the config ```amb-clean``` and then source the .amb script again to use Ambari 2.1.0

**Comment by shashank-inforworks** [comment]
Thanks for your help, you're right, I'm using an older version of the
script and I'm switching to the new one now.

On Mon, Sep 28, 2015 at 5:01 PM, Krisztian Horvath <notifications@github.com
