### ISSUE TITLE
add volume support

### ISSUE THREAD

**Issue by hdnebat** [sequenceiq/docker-ambari#90]
is it possible to have volume support?

**Comment by mhmxs** [comment]
Hi @hdnebat ,

If you are using ambari-functions, currently we have a [DOCKER_OPTS](https://github.com/sequenceiq/docker-ambari/blob/master/ambari-functions#L12) environment variable where you could pass for example volume support.
```
DOCKER_OPTS="-v /path:/path" . ambari-functions
```
Would this solve your issue?

**Comment by hdnebat** [comment]
great, many thanks
