### ISSUE TITLE
Docker swarm support?

### ISSUE THREAD

**Issue by yellowiscool** [sequenceiq/docker-ambari#96]
Hi,

Do you plan to support creating clusters running on Docker Swarm? I tried the current version but the network doesn't seem to work with multiple nodes in a swarm cluster. I think it might be possible to add support for [network overlays](https://docs.docker.com/engine/userguide/networking/dockernetworks/#an-overlay-network) in the ambari-functions script.

**Comment by yellowiscool** [comment]
I created a cluster using a network overlay, and it looks like everything works fine. I had to do the `_consul-register-service` by hand since the get-consul-ip IP wasn't accessible outside the network overlay.

In terms of performances, using the network overlay doesn't seem to be a problem, as far as I can see.

**Comment by martonsereg** [comment]
thanks for reporting it. The [Cloudbreak](https://github.com/sequenceiq/cloudbreak) project is already using this container through Swarm but with `net=host`, not overlay networks.
We didn't plan to add the network-overlay support to the ambari-functions script as it is rarely updated by us, but PRs are welcome if you manage to make it work in an automated way :)

**Comment by azimut** [comment]
There is any way to limit the cpu/memory usage of ambari? I mean on a vm I might like to use 100% of the resources. But on a physical host I might like to have ambari use up to certain amount of memory/cpu.

**Comment by mhmxs** [comment]
Hi @azimut , if you are using our ambari functions, there is (an empty) [DOCKER_OPTS](https://github.com/sequenceiq/docker-ambari/blob/master/ambari-functions#L13), so you just export your [docker options](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources). If you use one of our container, simply add options to the run command.
You have to know that i didn't try to limit memory and/or cpu, so i could imagine, if you set it too low, Ambari would fail.
