### ISSUE TITLE
cannot start container in windows

### ISSUE THREAD

**Issue by qinzhaokun** [sequenceiq/docker-ambari#99]
I install docker in my window computer and it runs hello-world successfully. When I pull sequence/ambari image, and start container using both ambari-function and command line, it not works, the error is shown: 

WARNING: Localhost DNS setting (--dns=127.0.0.1) may fail in containers.
2c6ae14af473d17e4b43b666ba7a086437364dcff20a5745b3c52c21492a5019
Error response from daemon: Cannot start container 2c6ae14af473d17e4b43b666ba7a0
86437364dcff20a5745b3c52c21492a5019: [8] System error: exec: "C:/Program Files/G
it/usr/local/serf/bin/start-serf-agent.sh": stat C:/Program Files/Git/usr/local/
serf/bin/start-serf-agent.sh: no such file or directory

zqin@L-SHC-00436827 MINGW64 ~

Anyone knows what wrong?

**Comment by AndriyKhavro** [comment]
I'm facing the same issue. Have you been able to resolve it?

**Comment by qinzhaokun** [comment]
@AndriyKhavro yes, I guess you must use Docker Quickstart terminal,  I resolve this issue by modifying the start common like "//tmp/serf/bin/start-serf-agent.sh", more easy way is opening virtualBox and sign in or opening other terminal (cygwin) and sign in, then all run smooth.

**Comment by tweise** [comment]
It works from within the docker machine VM, but not from bash on Windows. 

`docker-machine ssh your-vm-name`  then use tce to install bash (if it is not present) before installing and running the ambari functions.
